# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: MicrosoftSecurityDevOps@1
  displayName: "Run Microsoft Defender for Cloud Devops Security"
  inputs:
    command: 'run'
    categories: 'secrets,codes,artifacts,IaC,containers'
    tools: 'bandit,binskim,eslint,templateanalyzer,terrascan,trivy'
